image:
  repository: simonettifr/gitops-demo
  tag: "1.0.0"

containerPort: 8085

service:
  port: 8085

livenessProbe:
  path: /
  port: 8085
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  path: /
  port: 8085
  initialDelaySeconds: 10
  periodSeconds: 10
